language: ruby
addons:
  postgresql: "9.4"
cache: bundler
before_install:
  - bundle install
  - bundle exec rake db:setup
before_script:
  - psql -c 'create database Coreboot_Builder_test;' -U postgres
services:
  - postgresql
